const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const USERS={abu:{id:'350848',name:'Abu Jalloh',username:'abu',password:'audit123',credential:'Certified EWPros Auditor',initials:'AJ'},maria:{id:'350912',name:'Maria Kamara',username:'maria',password:'audit123',credential:'Certified EWPros Auditor',initials:'MK'}};
const seedAppointments=[
{id:'A-2649876',auditor:'abu',customer:'Devon Callan',date:'2026-07-15',time:'5:00 PM',address:'19705 Grayheaven Manor Road, Olney, MD 20832',status:'checked-in',tasks:{confirm:false,front:false,interior:false,exterior:false,terms:false},equipment:{interior:[],exterior:[]},photos:{front:null},notes:'',synced:true},
{id:'A-2648423',auditor:'abu',customer:'Robert Durr',date:'2026-07-21',time:'3:00 PM',address:'6504 Mink Hollow Road, Highland, MD 20777',status:'assigned',tasks:{confirm:false,front:false,interior:false,exterior:false,terms:false},equipment:{interior:[],exterior:[]},photos:{front:null},notes:'',synced:true},
{id:'A-2650031',auditor:'maria',customer:'Tina Brooks',date:'2026-07-22',time:'10:00 AM',address:'12150 Annapolis Road, Glenn Dale, MD 20769',status:'assigned',tasks:{confirm:false,front:false,interior:false,exterior:false,terms:false},equipment:{interior:[],exterior:[]},photos:{front:null},notes:'',synced:true}
];
const defaultNotes=[{title:'New Appointment!',body:'Appointment A-2649876 has been assigned to you.',date:'Jul 15, 2026 8:50 AM'},{title:'New Appointment!',body:'Appointment A-2648423 has been assigned to you.',date:'Jul 14, 2026 1:51 PM'}];
const EMAIL_FUNCTION_URL='/.netlify/functions/send-audit-email';
const EMAIL_QUEUE_KEY='aw_email_queue';
let state={user:null,route:'home',selectedAppointment:null,deferredPrompt:null};
function load(key,fallback){try{const v=localStorage.getItem(key);return v?JSON.parse(v):fallback}catch{return fallback}}
function save(key,v){localStorage.setItem(key,JSON.stringify(v))}
if(!localStorage.getItem('aw_appointments')) save('aw_appointments',seedAppointments);
if(!localStorage.getItem('aw_notifications')) save('aw_notifications',defaultNotes);
function appointments(){return load('aw_appointments',[])} function setAppointments(v){save('aw_appointments',v)}
function currentUser(){return USERS[state.user]}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),2200)}
function markDirty(){let q=load('aw_queue',0)+1;save('aw_queue',q);updateNetwork();if(navigator.onLine)setTimeout(()=>syncNow(false),500)}
function emailQueue(){return load(EMAIL_QUEUE_KEY,[])}
function setEmailQueue(queue){save(EMAIL_QUEUE_KEY,queue);updateNetwork()}
function updateAppointmentEmailStatus(appointmentId,status,error=''){
  const arr=appointments(),i=arr.findIndex(a=>a.id===appointmentId);
  if(i<0)return;
  arr[i].emailStatus=status;
  arr[i].emailError=error;
  if(status==='sent')arr[i].emailSentAt=new Date().toISOString();
  setAppointments(arr);
  if(state.user)render();
}
function buildAuditEmailRequest(a){
  const u=USERS[a.auditor]||currentUser();
  return {id:`audit-email-${a.id}-${a.completedAt}`,appointmentNumber:a.id,customerName:a.customer,auditorName:u?.name||'Unknown auditor',propertyAddress:a.address,completionDateTime:a.completedAt};
}
function queueAuditEmail(a){
  const queue=emailQueue(),request=buildAuditEmailRequest(a);
  if(!queue.some(item=>item.id===request.id))queue.push({...request,attempts:0,nextAttemptAt:0,lastError:''});
  setEmailQueue(queue);
  updateAppointmentEmailStatus(a.id,'queued');
  console.info('[Audit Email] Queued', {appointmentNumber:a.id, online:navigator.onLine});
  if(navigator.onLine)processEmailQueue({force:true});
  else toast('Audit saved. Email queued until internet reconnects.');
}
async function sendAuditEmail(item){
  const response=await fetch(EMAIL_FUNCTION_URL,{method:'POST',headers:{'Content-Type':'application/json','X-Idempotency-Key':item.id},body:JSON.stringify(item)});
  let body={};
  try{body=await response.json()}catch{body={message:`Server returned ${response.status}`}}
  if(!response.ok)throw new Error(body.error||body.message||`Email request failed (${response.status})`);
  return body;
}
let processingEmailQueue=false;
async function processEmailQueue({force=false}={}){
  if(processingEmailQueue||!navigator.onLine)return;
  processingEmailQueue=true;
  try{
    let queue=emailQueue(),changed=false;
    for(const item of [...queue]){
      if(!force&&item.nextAttemptAt&&Date.now()<item.nextAttemptAt)continue;
      try{
        console.info('[Audit Email] Sending', {appointmentNumber:item.appointmentNumber,attempt:item.attempts+1});
        const result=await sendAuditEmail(item);
        queue=queue.filter(q=>q.id!==item.id);changed=true;
        updateAppointmentEmailStatus(item.appointmentNumber,'sent');
        console.info('[Audit Email] Sent', {appointmentNumber:item.appointmentNumber,emailId:result.emailId});
        toast(`Email sent for ${item.appointmentNumber}`);
      }catch(error){
        const attempts=(item.attempts||0)+1;
        const delay=Math.min(15*60*1000,Math.pow(2,Math.min(attempts,6))*15000);
        const target=queue.find(q=>q.id===item.id);
        if(target){target.attempts=attempts;target.lastError=error.message;target.nextAttemptAt=Date.now()+delay;changed=true}
        updateAppointmentEmailStatus(item.appointmentNumber,'failed',error.message);
        console.error('[Audit Email] Send failed', {appointmentNumber:item.appointmentNumber,attempts,error});
        toast(`Email failed for ${item.appointmentNumber}; it will retry automatically.`);
      }
    }
    if(changed)setEmailQueue(queue);
  }finally{processingEmailQueue=false;updateNetwork()}
}
async function syncNow(showToast=true){
  if(!navigator.onLine){toast('Offline — changes and email notifications remain queued.');return}
  save('aw_queue',0);const a=appointments().map(x=>({...x,synced:true}));setAppointments(a);
  await processEmailQueue({force:true});updateNetwork();if(showToast&&!emailQueue().length)toast('Audit data synchronized')
}
function updateNetwork(){
  const online=navigator.onLine,q=load('aw_queue',0),emails=emailQueue().length,total=q+emails;
  $('#syncbar').classList.toggle('offline',!online);$('#networkText').textContent=online?'Online':'Offline — saved on device';
  $('#syncText').textContent=total?`${q} data change${q===1?'':'s'} and ${emails} email${emails===1?'':'s'} waiting`:'All changes saved';
}
function avatar(u,large=false){return `<div class="avatar ${large?'avatar-lg':''}" style="display:grid;place-items:center;background:#dbeafe;font-weight:800;font-size:${large?28:20}px">${u.initials}</div>`}
function setRoute(route,param){state.route=route;state.selectedAppointment=param||state.selectedAppointment;render();window.scrollTo(0,0)}
function header(title){$('#headerTitle').textContent=title}
function home(){const u=currentUser();header('Auditor Wizard');return `<div class="profile">${avatar(u)}<div><strong>${u.name}</strong><div class="small">Inspector ID: ${u.id}</div></div></div><div class="card"><button class="menu-item" data-go="badge"><span class="menu-icon" style="background:#a5b4fc">▣</span><strong>Badge</strong><span class="chev">›</span></button><button class="menu-item" data-go="audits"><span class="menu-icon" style="background:#f59e0b">♟</span><strong>Audits</strong><span class="badge-count">${load('aw_notifications',[]).length} unread</span></button><button class="menu-item" data-go="settings"><span class="menu-icon" style="background:#3b82f6">⚙</span><strong>Settings</strong><span class="chev">›</span></button><button class="menu-item" data-go="support"><span class="menu-icon" style="background:#ef6b6b">☎</span><strong>Support</strong><span class="chev">›</span></button></div><button class="secondary full" id="syncNow">Synchronize now</button>`}
function badge(){const u=currentUser();header('Auditor Badge');return `<div class="screen-title"><button class="back" data-go="home">‹</button><h2>Auditor Badge</h2></div><div class="card badge-card"><div class="badge-head"><span>EWPros</span><span class="badge-brand">A</span></div><div class="badge-body"><div style="display:flex;justify-content:space-between;align-items:center"><div><h2>${u.name}</h2><div class="small">Badge Number</div><strong>${u.id}</strong><p class="small">Credentials<br><strong>${u.credential}</strong></p></div>${avatar(u,true)}</div><p style="text-align:center;font-weight:700">Expertise. Experience. Accuracy.</p><canvas id="qr" class="qr" width="130" height="130"></canvas></div></div>`}
function drawPseudoQR(){const c=$('#qr');if(!c)return;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,130,130);x.fillStyle='#d50032';let seed=[...`${currentUser().id}-${currentUser().name}`].reduce((a,c)=>a+c.charCodeAt(0),0);for(let r=0;r<21;r++)for(let col=0;col<21;col++){seed=(seed*9301+49297)%233280;if(seed/233280>.48)x.fillRect(col*6+2,r*6+2,5,5)}[[0,0],[14,0],[0,14]].forEach(([a,b])=>{x.fillStyle='#d50032';x.fillRect(a*6+2,b*6+2,42,42);x.fillStyle='#fff';x.fillRect(a*6+8,b*6+8,30,30);x.fillStyle='#d50032';x.fillRect(a*6+14,b*6+14,18,18)})}
function audits(){header('Notifications');return `<div class="screen-title"><button class="back" data-go="home">‹</button><h2>Notifications</h2></div><div class="card">${load('aw_notifications',[]).map(n=>`<div class="note-item"><div class="bell">♟</div><div><strong>${n.title}</strong><div class="small">${n.body}</div><div class="small muted">${n.date}</div></div></div>`).join('')}</div>`}
function settings(){header('Settings');const opts=['Push notifications are enabled','Photo gallery write access is enabled','Photo gallery read access is enabled','Camera access is enabled'];return `<div class="screen-title"><button class="back" data-go="home">‹</button><h2>Settings</h2></div><div class="card"><h3 style="color:var(--red)">Notifications</h3>${opts.map((o,i)=>`<div class="status-line"><span>${o}</span><span class="toggle on"></span></div>`).join('')}<div class="status-line"><span>Offline storage</span><span class="pill">Ready</span></div><div class="status-line"><span>Pending data sync items</span><strong>${load('aw_queue',0)}</strong></div><div class="status-line"><span>Pending email notifications</span><strong>${emailQueue().length}</strong></div></div><button class="primary full" id="installAction">Install on this device</button>`}
function support(){header('Inspection Wizard');return `<div class="screen-title"><button class="back" data-go="home">‹</button><h2>Inspection Wizard</h2></div><div class="card" style="text-align:center"><h3>Need Support?</h3><p>We're here to help.</p><p>Call Toll Free <a href="tel:8884075407" style="color:var(--red);font-weight:800">(888) 407-5407</a></p><p>Call Admin <a href="tel:8889808407" style="color:var(--red);font-weight:800">(888) 980-8407</a></p><p><a href="mailto:support@ewpros.com">support@ewpros.com</a></p></div>`}
function appointmentsView(){header('Appointments');const list=appointments().filter(a=>a.auditor===state.user);return `<h2>Appointments</h2>${list.map(a=>{let done=Object.values(a.tasks).filter(Boolean).length;return `<div class="card appt" data-open-appt="${a.id}"><div style="display:flex;justify-content:space-between"><span class="pill">⚡ Appointment</span><strong>${a.id}</strong></div><h3>${a.customer}</h3><div class="meta"><div>📅 ${a.date}<br>🕒 ${a.time}</div><div>📍 ${a.address}</div></div><div class="progress"><div class="step"><span class="dot ${a.status!=='assigned'?'done':''}"></span>Day of Appointment</div><span class="connector"></span><div class="step"><span class="dot ${['checked-in','ready','completed'].includes(a.status)?'done':''}"></span>Checked In</div><span class="connector"></span><div class="step"><span class="dot ${done===5?'done':''}"></span>Ready to Check Out</div></div><div class="small muted" style="margin-top:10px">${done}/5 required sections complete · ${a.synced?'Synced':'Waiting to sync'}${a.status==='completed'?` · Email: ${a.emailStatus==='sent'?'Sent':a.emailStatus==='failed'?'Retry pending':'Queued'}`:''}</div></div>`}).join('')}`}
function taskRow(key,label){const a=getAppt();const done=a.tasks[key];return `<div class="task" data-task="${key}"><span class="task-icon">●</span><strong>${label}</strong><span class="task-status ${done?'done':''}">${done?'✓':'!'}</span></div>`}
function appointmentDetail(){const a=getAppt();header(a.id);if(!a)return '<p>Appointment not found.</p>';const all=Object.values(a.tasks).every(Boolean);return `<div class="screen-title"><button class="back" data-go="appointments">‹</button><div><h2 style="margin:0">${a.customer}</h2><div class="small muted">${a.id} · ${a.address}</div></div></div><div class="card"><div class="toolbar"><button class="secondary" id="checkin">${a.status==='assigned'?'Check in':'Checked in ✓'}</button><button class="secondary" id="exportAudit">Export audit</button></div>${taskRow('confirm','Confirm Address & Account #')}${taskRow('front','Picture of Building Front')}${taskRow('interior','Interior Equipment')}${taskRow('exterior','Exterior Equipment')}${taskRow('terms','Customer T & C')}</div>${a.status==='completed'?`<div class="card"><strong>Email notification</strong><div class="small muted">${a.emailStatus==='sent'?'Sent successfully':a.emailStatus==='failed'?`Retry pending: ${a.emailError||'Temporary error'}`:'Queued for sending'}</div></div>`:''}<button class="primary full" id="checkout" ${all&&a.status!=='completed'?'':'disabled'} style="opacity:${all&&a.status!=='completed'?1:.45}">${a.status==='completed'?'Audit completed':all?'Complete & Check Out':'Complete all required sections'}</button>`}
function getAppt(){return appointments().find(a=>a.id===state.selectedAppointment)}
function mutateAppt(fn){const arr=appointments();const i=arr.findIndex(a=>a.id===state.selectedAppointment);fn(arr[i]);arr[i].synced=false;setAppointments(arr);markDirty()}
function confirmView(){const a=getAppt();header('Confirm Appointment');return `<div class="screen-title"><button class="back" data-go="appointment">‹</button><h2>Confirm Address & Account</h2></div><div class="card"><div class="field"><label>Customer</label><input id="cust" value="${a.customer}"></div><div class="field"><label>Service Address</label><textarea id="addr">${a.address}</textarea></div><div class="field"><label>Utility Account Number</label><input id="acct" value="${a.account||''}" placeholder="Enter account number"></div><label class="checkline"><input id="verified" type="checkbox" ${a.tasks.confirm?'checked':''}> I verified the address and account number</label></div><button class="primary full" id="saveConfirm">Save section</button>`}
function frontView(){const a=getAppt();header('Building Front');return `<div class="screen-title"><button class="back" data-go="appointment">‹</button><h2>Picture of Building Front</h2></div><div class="card"><div class="field"><label>Take or select photo</label><input id="frontPhoto" type="file" accept="image/*" capture="environment"></div>${a.photos.front?`<img class="photo-preview" src="${a.photos.front}">`:'<div class="empty">No photo added</div>'}</div><button class="primary full" id="saveFront">Save section</button>`}
function equipmentView(type){const a=getAppt();const items=a.equipment[type]||[];header(type==='interior'?'Interior Equipment':'Exterior Equipment');return `<div class="screen-title"><button class="back" data-go="appointment">‹</button><h2>${type==='interior'?'Interior':'Exterior'} Equipment</h2></div><div class="toolbar"><button class="primary" id="addEquipment">+ Add equipment</button><button class="secondary" id="noEquipment">No equipment present</button></div>${items.length?items.map((e,i)=>`<div class="card equipment"><h4>${e.category||'Equipment'} — ${e.type||'Unspecified'}</h4><div class="small">${e.manufacturer||''} ${e.model||''}</div><div class="small muted">Location: ${e.location||'Not entered'} · Qty: ${e.quantity||1}</div><div class="toolbar"><button class="secondary" data-edit-eq="${i}">Edit</button><button class="danger" data-delete-eq="${i}">Delete</button></div></div>`).join(''):'<div class="card empty">No equipment has been added.</div>'}<button class="primary full" id="finishEquipment" ${items.length||a.noEquipment?.[type]?'':'disabled'}>Save section</button>`}
function equipmentForm(type,index=null){const a=getAppt(),e=index===null?{}:a.equipment[type][index];header('Equipment Entry');return `<div class="screen-title"><button class="back" data-go="${type}">‹</button><h2>${index===null?'Add':'Edit'} Equipment</h2></div><form id="eqForm" class="card"><div class="row"><div class="field"><label>Category</label><select id="eqCategory"><option>HVAC</option><option>Lighting</option><option>Water Heating</option><option>Refrigeration</option><option>Other</option></select></div><div class="field"><label>Equipment type</label><input id="eqType" value="${e.type||''}" placeholder="Heat pump"></div></div><div class="row"><div class="field"><label>Manufacturer</label><input id="eqMfr" value="${e.manufacturer||''}"></div><div class="field"><label>Model</label><input id="eqModel" value="${e.model||''}"></div></div><div class="row"><div class="field"><label>Serial number</label><input id="eqSerial" value="${e.serial||''}"></div><div class="field"><label>Quantity</label><input id="eqQty" type="number" min="1" value="${e.quantity||1}"></div></div><div class="field"><label>Location</label><input id="eqLocation" value="${e.location||''}"></div><div class="row"><div class="field"><label>Capacity</label><input id="eqCapacity" value="${e.capacity||''}" placeholder="3 tons"></div><div class="field"><label>Efficiency</label><input id="eqEfficiency" value="${e.efficiency||''}" placeholder="16 SEER"></div></div><div class="field"><label>Condition</label><select id="eqCondition"><option>Good</option><option>Fair</option><option>Poor</option><option>Not operating</option></select></div><div class="field"><label>Notes</label><textarea id="eqNotes">${e.notes||''}</textarea></div><button class="primary full" type="submit">Save equipment</button></form>`}
function termsView(){const a=getAppt();header('Customer T & C');return `<div class="screen-title"><button class="back" data-go="appointment">‹</button><h2>Customer Terms & Conditions</h2></div><div class="card"><p class="small">The customer confirms that the auditor has permission to inspect accessible equipment, take audit-related photos, and record information required for the energy assessment.</p><div class="field"><label>Customer name</label><input id="signName" value="${a.signatureName||a.customer}"></div><label class="checkline"><input id="acceptTerms" type="checkbox" ${a.tasks.terms?'checked':''}> Customer accepts the terms and conditions</label><div class="field" style="margin-top:12px"><label>Signature</label><input id="signature" value="${a.signature||''}" placeholder="Type customer name as signature"></div></div><button class="primary full" id="saveTerms">Save section</button>`}
function render(){if(!state.user)return;$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route || (state.route==='appointment'&&b.dataset.route==='appointments')));let html='';switch(state.route){case'home':html=home();break;case'badge':html=badge();break;case'audits':html=audits();break;case'settings':html=settings();break;case'support':html=support();break;case'appointments':html=appointmentsView();break;case'appointment':html=appointmentDetail();break;case'confirm':html=confirmView();break;case'front':html=frontView();break;case'interior':html=equipmentView('interior');break;case'exterior':html=equipmentView('exterior');break;case'eqform':html=equipmentForm(state.eqType,state.eqIndex);break;case'terms':html=termsView();break}$('#view').innerHTML=html;bind();if(state.route==='badge')drawPseudoQR()}
function bind(){$$('[data-go]').forEach(x=>x.onclick=()=>setRoute(x.dataset.go));$$('.nav-btn').forEach(x=>x.onclick=()=>setRoute(x.dataset.route));$$('[data-open-appt]').forEach(x=>x.onclick=()=>setRoute('appointment',x.dataset.openAppt));$('#syncNow')?.addEventListener('click',syncNow);$('#installAction')?.addEventListener('click',installApp);$('#checkin')?.addEventListener('click',()=>{mutateAppt(a=>a.status='checked-in');render()});
$$('[data-task]').forEach(x=>x.onclick=()=>setRoute(x.dataset.task));
$('#saveConfirm')?.addEventListener('click',()=>{if(!$('#acct').value.trim()||!$('#verified').checked)return toast('Enter account number and verify the information');mutateAppt(a=>{a.customer=$('#cust').value;a.address=$('#addr').value;a.account=$('#acct').value;a.tasks.confirm=true});setRoute('appointment')});
let pendingPhoto=null;$('#frontPhoto')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{pendingPhoto=r.result;const old=$('.photo-preview');if(old)old.src=pendingPhoto;else e.target.closest('.card').insertAdjacentHTML('beforeend',`<img class="photo-preview" src="${pendingPhoto}">`)};r.readAsDataURL(f)});$('#saveFront')?.addEventListener('click',()=>{const a=getAppt();if(!pendingPhoto&&!a.photos.front)return toast('Add a building-front photo');mutateAppt(a=>{if(pendingPhoto)a.photos.front=pendingPhoto;a.tasks.front=true});setRoute('appointment')});
$('#addEquipment')?.addEventListener('click',()=>{state.eqType=state.route;state.eqIndex=null;setRoute('eqform')});$$('[data-edit-eq]').forEach(x=>x.onclick=()=>{state.eqType=state.route;state.eqIndex=Number(x.dataset.editEq);setRoute('eqform')});$$('[data-delete-eq]').forEach(x=>x.onclick=()=>{if(confirm('Delete this equipment record?')){mutateAppt(a=>a.equipment[state.route].splice(Number(x.dataset.deleteEq),1));render()}});$('#noEquipment')?.addEventListener('click',()=>{mutateAppt(a=>{a.noEquipment=a.noEquipment||{};a.noEquipment[state.route]=true});render();toast('Marked as no equipment present')});$('#finishEquipment')?.addEventListener('click',()=>{const type=state.route;mutateAppt(a=>a.tasks[type]=true);setRoute('appointment')});
$('#eqForm')?.addEventListener('submit',e=>{e.preventDefault();const obj={category:$('#eqCategory').value,type:$('#eqType').value,manufacturer:$('#eqMfr').value,model:$('#eqModel').value,serial:$('#eqSerial').value,quantity:Number($('#eqQty').value)||1,location:$('#eqLocation').value,capacity:$('#eqCapacity').value,efficiency:$('#eqEfficiency').value,condition:$('#eqCondition').value,notes:$('#eqNotes').value};mutateAppt(a=>{if(state.eqIndex===null)a.equipment[state.eqType].push(obj);else a.equipment[state.eqType][state.eqIndex]=obj});setRoute(state.eqType)});
$('#saveTerms')?.addEventListener('click',()=>{if(!$('#acceptTerms').checked||!$('#signature').value.trim())return toast('Customer acceptance and signature are required');mutateAppt(a=>{a.signatureName=$('#signName').value;a.signature=$('#signature').value;a.tasks.terms=true});setRoute('appointment')});
$('#checkout')?.addEventListener('click',()=>{let completed;mutateAppt(a=>{a.status='completed';a.completedAt=new Date().toISOString();a.emailStatus='queued';a.emailError='';completed={...a}});queueAuditEmail(completed);toast(navigator.onLine?'Audit completed. Sending email…':'Audit completed and saved offline. Email queued.');setRoute('appointments')});$('#exportAudit')?.addEventListener('click',()=>downloadJSON(getAppt()));}
function downloadJSON(obj){const b=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`${obj.id}-audit.json`;a.click();URL.revokeObjectURL(u)}
async function installApp(){if(state.deferredPrompt){state.deferredPrompt.prompt();await state.deferredPrompt.userChoice;state.deferredPrompt=null}else toast('Use your browser menu and choose “Add to Home Screen”')}
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();const u=$('#username').value.trim().toLowerCase(),p=$('#password').value;if(!USERS[u]||USERS[u].password!==p){$('#loginError').textContent='Invalid username or password';$('#loginError').classList.remove('hidden');return}state.user=u;save('aw_session',u);$('#login').classList.add('hidden');$('#app').classList.remove('hidden');updateNetwork();render()});
$('#logoutBtn').onclick=()=>{localStorage.removeItem('aw_session');state.user=null;$('#app').classList.add('hidden');$('#login').classList.remove('hidden')};$('#installBtn').onclick=installApp;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredPrompt=e});window.addEventListener('online',()=>{updateNetwork();syncNow(false)});window.addEventListener('offline',updateNetwork);
setInterval(()=>processEmailQueue(),60000);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');const session=load('aw_session',null);if(session&&USERS[session]){state.user=session;$('#login').classList.add('hidden');$('#app').classList.remove('hidden');updateNetwork();render();if(navigator.onLine)processEmailQueue()}
