window.EWPROS_PDATA = {
  "columns": [
    {
      "key": "proposeMeasure",
      "label": "Propose Measure"
    },
    {
      "key": "measureType",
      "label": "Measure Type"
    },
    {
      "key": "measureDescription",
      "label": "Measure Description"
    },
    {
      "key": "measureCode",
      "label": "Measure Code"
    },
    {
      "key": "ledManufacturer",
      "label": "LED Manufacturer"
    },
    {
      "key": "modelNumber",
      "label": "Model Number"
    },
    {
      "key": "proposedQty",
      "label": "Proposed Qty"
    },
    {
      "key": "proposedTotalUnits",
      "label": "Proposed Total Units"
    },
    {
      "key": "lumensPerFixture",
      "label": "Lumens / Fixture"
    },
    {
      "key": "wattsPerFixture",
      "label": "Watts / Fixture"
    },
    {
      "key": "efficacyPerDevice",
      "label": "Efficacy / Proposed Device"
    },
    {
      "key": "inc",
      "label": "INC"
    },
    {
      "key": "inc2",
      "label": "INC 2"
    },
    {
      "key": "dlcEnergyStarId",
      "label": "DLC / Energy Star ID"
    },
    {
      "key": "reportedModelNumber",
      "label": "Reported Model Number"
    },
    {
      "key": "reportedLumens",
      "label": "Reported Lumens"
    },
    {
      "key": "reportedWattage",
      "label": "Reported Wattage"
    },
    {
      "key": "reportedEfficacy",
      "label": "Reported Efficacy"
    }
  ],
  "rows": [
    {
      "proposeMeasure": "(2x4)LED40W",
      "measureType": "LED Troffer Luminaires",
      "measureDescription": "New LED troffer for 2x4 luminaires",
      "measureCode": "RL 101",
      "ledManufacturer": "Builders Pack",
      "modelNumber": "44-6012-40W-40K-TR2-D-[N;S]-B",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "5226",
      "wattsPerFixture": "41.3",
      "efficacyPerDevice": "126.54",
      "inc": "$100",
      "inc2": "$350.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "44-6012-40W-40K-TR2-D-[N;S]-B",
      "reportedLumens": "5226",
      "reportedWattage": "41.3",
      "reportedEfficacy": "126.54"
    },
    {
      "proposeMeasure": "(2x2)LED20W",
      "measureType": "LED Troffer Luminaires",
      "measureDescription": "New LED troffer for 2x2 and 1x4 luminaires",
      "measureCode": "RL102",
      "ledManufacturer": "Builders Pack",
      "modelNumber": "CR20-20W-22-40K-D-S",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "2504.98",
      "wattsPerFixture": "20.15",
      "efficacyPerDevice": "124.32",
      "inc": "$70",
      "inc2": "$245.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "CR20-20W-22-40K-D-S",
      "reportedLumens": "2504.98",
      "reportedWattage": "20.15",
      "reportedEfficacy": "124.32"
    },
    {
      "proposeMeasure": "(1x4)LED40W_SM",
      "measureType": "LED Linear Ambient/Stairwell Luminaires",
      "measureDescription": "New LED linear ambient luminaire - Strip or Wrap fixtures",
      "measureCode": "RL 111B",
      "ledManufacturer": "Builders Pack",
      "modelNumber": "TR11-24W-120-40K",
      "proposedQty": "4",
      "proposedTotalUnits": "",
      "lumensPerFixture": "3193.5",
      "wattsPerFixture": "24.46",
      "efficacyPerDevice": "130.56",
      "inc": "$48",
      "inc2": "$168.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "TR11-24W-120-40K",
      "reportedLumens": "3193.5",
      "reportedWattage": "24.46",
      "reportedEfficacy": "130.56"
    },
    {
      "proposeMeasure": "(1x4)LED40W_Stairwell",
      "measureType": "LED Linear Ambient/Stairwell Luminaires",
      "measureDescription": "New LED stairwell luminaire",
      "measureCode": "RL 112",
      "ledManufacturer": "Builders Pack",
      "modelNumber": "TR11-24W-120-40K",
      "proposedQty": "4",
      "proposedTotalUnits": "",
      "lumensPerFixture": "3193.5",
      "wattsPerFixture": "24.46",
      "efficacyPerDevice": "130.56",
      "inc": "$100",
      "inc2": "$350.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "TR11-24W-120-40K",
      "reportedLumens": "3193.5",
      "reportedWattage": "24.46",
      "reportedEfficacy": "130.56"
    },
    {
      "proposeMeasure": "(1x8)LED64W_SM",
      "measureType": "LED Linear Ambient/Stairwell Luminaires",
      "measureDescription": "New LED linear ambient luminaire - Strip or Wrap fixtures",
      "measureCode": "",
      "ledManufacturer": "Builders Pack",
      "modelNumber": "TR12-64W-240-40K-PDN-A",
      "proposedQty": "8",
      "proposedTotalUnits": "",
      "lumensPerFixture": "8394.5",
      "wattsPerFixture": "63.39",
      "efficacyPerDevice": "132.42",
      "inc": "$96",
      "inc2": "$336.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "TR12-64W-240-40K-PDN-A",
      "reportedLumens": "8394.5",
      "reportedWattage": "63.39",
      "reportedEfficacy": "132.42"
    },
    {
      "proposeMeasure": "4ft Integrated Strip Light (LB)",
      "measureType": "LED High/Low Bay Luminaires",
      "measureDescription": "New LED high/low bay luminaire - 5,000 lm  - 9,999 lm",
      "measureCode": "RL 141",
      "ledManufacturer": "Builders Pack",
      "modelNumber": "EPA36-T8AL-120-730-840-[5.8G,DDS,TR,APP]",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "5218.99",
      "wattsPerFixture": "34.28",
      "efficacyPerDevice": "152.2",
      "inc": "$125",
      "inc2": "$437.50",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "EPA36-T8AL-120-730-840-[5.8G,DDS,TR,APP]",
      "reportedLumens": "5218.99",
      "reportedWattage": "34.28",
      "reportedEfficacy": "152.2"
    },
    {
      "proposeMeasure": "WP_LED54W",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 5,000 lm - 9,999 lm",
      "measureCode": "RL 152",
      "ledManufacturer": "GreenTek Energy Systems",
      "modelNumber": "GT-SWP-55W-LB[S;blank][R;balnk][P;balnk][-a40K",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "7033.9",
      "wattsPerFixture": "54.38",
      "efficacyPerDevice": "129.35",
      "inc": "$200",
      "inc2": "$700.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "GT-SWP-55W-LB[S;blank][R;balnk][P;balnk][-a40K",
      "reportedLumens": "7033.9",
      "reportedWattage": "54.38",
      "reportedEfficacy": "129.35"
    },
    {
      "proposeMeasure": "WP_LED60W",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 5,000 lm - 9,999 lm",
      "measureCode": "RL 152",
      "ledManufacturer": "GreenTek Energy Systems",
      "modelNumber": "GT-SSWP-60W-LB[S;Blank][M;Bkank]-50K",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "7601.8",
      "wattsPerFixture": "60.26",
      "efficacyPerDevice": "126.15",
      "inc": "$200",
      "inc2": "$700.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "GT-SSWP-60W-LB[S;Blank][M;Bkank]-50K",
      "reportedLumens": "7601.8",
      "reportedWattage": "60.26",
      "reportedEfficacy": "126.15"
    },
    {
      "proposeMeasure": "WP_LED80W_Venas",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 10,000 lm - 19,999 lm",
      "measureCode": "RL 153",
      "ledManufacturer": "Venas Co., Limited",
      "modelNumber": "WP-80WI2D50H",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "11520",
      "wattsPerFixture": "80",
      "efficacyPerDevice": "144",
      "inc": "$250",
      "inc2": "$875.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "WP-80WI2D50H",
      "reportedLumens": "11520",
      "reportedWattage": "80",
      "reportedEfficacy": "144"
    },
    {
      "proposeMeasure": "WP_81W_11Klm_5KCCT",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 10,000 lm - 19,999 lm",
      "measureCode": "RL 153",
      "ledManufacturer": "RuggedGrade",
      "modelNumber": "RGL-DURADOBLADE-80WBSPSA1-ab50",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "11386",
      "wattsPerFixture": "81.1",
      "efficacyPerDevice": "140.38",
      "inc": "$300",
      "inc2": "$1,050.00",
      "dlcEnergyStarId": "S-H3ZWXB",
      "reportedModelNumber": "RGL-DURADOBLADE-80WBSPSA1-ab50",
      "reportedLumens": "11386",
      "reportedWattage": "81.1",
      "reportedEfficacy": "140.38"
    },
    {
      "proposeMeasure": "WP_LED119W",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 10,000 lm - 19,999 lm",
      "measureCode": "RL 153",
      "ledManufacturer": "GreenTek Energy Systems",
      "modelNumber": "GT-SWP-120W-LB[S;blank][R;blank][P;blank]-a50K",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "15517.3",
      "wattsPerFixture": "119.5",
      "efficacyPerDevice": "129.85",
      "inc": "$250",
      "inc2": "$875.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "GT-SWP-120W-LB[S;blank][R;blank][P;blank]-a50K",
      "reportedLumens": "15517.3",
      "reportedWattage": "119.5",
      "reportedEfficacy": "129.85"
    },
    {
      "proposeMeasure": "WP_LED201W",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 20,000 lm - 29,999 lm",
      "measureCode": "RL 154",
      "ledManufacturer": "RuggedGrade",
      "modelNumber": "RGL-SCOWP01B-200BA1-a[S;Blank][P;Blank]57",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "25792.9",
      "wattsPerFixture": "201.13",
      "efficacyPerDevice": "128.24",
      "inc": "$350",
      "inc2": "$1,225.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "RGL-SCOWP01B-200BA1-a[S;Blank][P;Blank]57",
      "reportedLumens": "25792.9",
      "reportedWattage": "201.13",
      "reportedEfficacy": "128.24"
    },
    {
      "proposeMeasure": "WP_203W_25Klm_5KCCT",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 20,000 lm - 29,999 lm",
      "measureCode": "RL 154",
      "ledManufacturer": "RuggedGrade",
      "modelNumber": "RGL-SCOWP01B-200WBA1-abcd50",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "25012",
      "wattsPerFixture": "202.5",
      "efficacyPerDevice": "123.55",
      "inc": "$400",
      "inc2": "$1,400.00",
      "dlcEnergyStarId": "S-WIVGMJ",
      "reportedModelNumber": "RGL-SCOWP01B-200WBA1-abcd50",
      "reportedLumens": "25012",
      "reportedWattage": "202.5",
      "reportedEfficacy": "123.55"
    },
    {
      "proposeMeasure": "FLD_49W_6Klm_3KCCT",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 5,000 lm - 9,999 lm",
      "measureCode": "RL 152",
      "ledManufacturer": "Super Bright LEDs",
      "modelNumber": "FLCCT2-Zd-SP50-Xyabc",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "6260",
      "wattsPerFixture": "49.1",
      "efficacyPerDevice": "127.39",
      "inc": "$250",
      "inc2": "$875.00",
      "dlcEnergyStarId": "S-KDIHX8",
      "reportedModelNumber": "FLCCT2-Zd-SP50-Xyabc",
      "reportedLumens": "6260",
      "reportedWattage": "49.1",
      "reportedEfficacy": "127.39"
    },
    {
      "proposeMeasure": "FLD_LED49W",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 5,000 lm - 9,999 lm",
      "measureCode": "RL 152",
      "ledManufacturer": "GreenTek Energy Systems",
      "modelNumber": "GT-FL06-50WCT1A1-40K",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "5778",
      "wattsPerFixture": "49.18",
      "efficacyPerDevice": "117.49",
      "inc": "$200",
      "inc2": "$700.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "GT-FL06-50WCT1A1-40K",
      "reportedLumens": "5778",
      "reportedWattage": "49.18",
      "reportedEfficacy": "117.49"
    },
    {
      "proposeMeasure": "FLD_89W_11Klm_5KCCT",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 10,000 lm - 19,999 lm",
      "measureCode": "RL 153",
      "ledManufacturer": "Cooper Lighting Solutions",
      "modelNumber": "NFFLD-C25-D-[Voltage Includes UNV & 347]-33-[All Mounting]-[All Color]-7050-[PER, PER7, 10K, D10, MSP/DIM-L12, MSP/DIM-L30, MSP-L12, MSP-L30]",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "11927.8",
      "wattsPerFixture": "89.5",
      "efficacyPerDevice": "133.2715084",
      "inc": "$300",
      "inc2": "$1,050.00",
      "dlcEnergyStarId": "PFAAC78C",
      "reportedModelNumber": "NFFLD-C25-D-[Voltage Includes UNV & 347]-33-[All Mounting]-[All Color]-7050-[PER, PER7, 10K, D10, MSP/DIM-L12, MSP/DIM-L30, MSP-L12, MSP-L30]",
      "reportedLumens": "11927.8",
      "reportedWattage": "89.5",
      "reportedEfficacy": "133.2715084"
    },
    {
      "proposeMeasure": "FLD_LED97W",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 10,000 lm - 19,999 lm",
      "measureCode": "RL 153",
      "ledManufacturer": "GreenTek Energy Systems",
      "modelNumber": "GT-S-G04-100WAT3A14000K[Mounting type C,D][Blank,PC][Blank,S]",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "12292",
      "wattsPerFixture": "97.93",
      "efficacyPerDevice": "125.52",
      "inc": "$250",
      "inc2": "$875.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "GT-S-G04-100WAT3A14000K[Mounting type C,D][Blank,PC][Blank,S]",
      "reportedLumens": "12292",
      "reportedWattage": "97.93",
      "reportedEfficacy": "125.52"
    },
    {
      "proposeMeasure": "FLD_100W_13Klm_5KCCT",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 10,000 lm - 19,999 lm",
      "measureCode": "RL 154",
      "ledManufacturer": "Shanghai Supertek Lighting Co., Ltd",
      "modelNumber": "WP07B-100MW-50KMC-MV-[Blank or D0 to D9]-[Blank or P0 to P9]-[Blank or S0 to S9]-[Blank or -AA to -XX]-D-V40",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "13000",
      "wattsPerFixture": "100",
      "efficacyPerDevice": "130",
      "inc": "$300",
      "inc2": "$1,050.00",
      "dlcEnergyStarId": "S-ZSPIL5",
      "reportedModelNumber": "WP07B-100MW-50KMC-MV-[Blank or D0 to D9]-[Blank or P0 to P9]-[Blank or S0 to S9]-[Blank or -AA to -XX]-D-V40",
      "reportedLumens": "13000",
      "reportedWattage": "100",
      "reportedEfficacy": "130"
    },
    {
      "proposeMeasure": "FLD_LED207W",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 30,000 lm - 39,999 lm",
      "measureCode": "RL 155",
      "ledManufacturer": "RAD Lightning",
      "modelNumber": "FXLED200[SF,T][blank,W]/B/[blank,PCS,PCS2,PCT,7PR,SP,LC]",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "30306",
      "wattsPerFixture": "207.3",
      "efficacyPerDevice": "146.2",
      "inc": "$400",
      "inc2": "$1,400.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "FXLED200[SF,T][blank,W]/B/[blank,PCS,PCS2,PCT,7PR,SP,LC]",
      "reportedLumens": "30306",
      "reportedWattage": "207.3",
      "reportedEfficacy": "146.2"
    },
    {
      "proposeMeasure": "PLT_LED149W",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 10,000 lm - 19,999 lm",
      "measureCode": "RL 153",
      "ledManufacturer": "GreenTek Energy Systems",
      "modelNumber": "GT-AL2-150W-N-DLgb[M;Blank]fJ3-a57Ke",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "19984.9",
      "wattsPerFixture": "149.21",
      "efficacyPerDevice": "133.94",
      "inc": "$250",
      "inc2": "$875.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "GT-AL2-150W-N-DLgb[M;Blank]fJ3-a57Ke",
      "reportedLumens": "19984.9",
      "reportedWattage": "149.21",
      "reportedEfficacy": "133.94"
    },
    {
      "proposeMeasure": "PLT_LED153W",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 20,000 lm - 29,999 lm",
      "measureCode": "RL 154",
      "ledManufacturer": "Shenzhen CGT Technology Co,. Ltd",
      "modelNumber": "PKB-150W277-57K-X-T3-Y-Z",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "20820.4",
      "wattsPerFixture": "153.4",
      "efficacyPerDevice": "135.7",
      "inc": "$350",
      "inc2": "$1,225.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "PKB-150W277-57K-X-T3-Y-Z",
      "reportedLumens": "20820.4",
      "reportedWattage": "153.4",
      "reportedEfficacy": "135.7"
    },
    {
      "proposeMeasure": "PLT_LED196W",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 30,000 lm - 39,999 lm",
      "measureCode": "RL 155",
      "ledManufacturer": "Shenzhen Longsun Optoelectronics Technology Co. Ltd",
      "modelNumber": "CES-LS-FT-200W50FBT4-[UPM;APM;SFM;TM][S1;S2;S3;Blank][BZ;BLWH;SL;OT]",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "30184.04863",
      "wattsPerFixture": "196.5",
      "efficacyPerDevice": "153.60839",
      "inc": "$400",
      "inc2": "$1,400.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "CES-LS-FT-200W50FBT4-[UPM;APM;SFM;TM][S1;S2;S3;Blank][BZ;BLWH;SL;OT]",
      "reportedLumens": "30184.04863",
      "reportedWattage": "196.5",
      "reportedEfficacy": "153.60839"
    },
    {
      "proposeMeasure": "PLT_LED200W_PKB",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 30,000 lm - 39,999 lm",
      "measureCode": "RL 155",
      "ledManufacturer": "Shenzhen CGT Technology Co.,Ltd",
      "modelNumber": "PKB-200W277-57K-X-T3-Y-Z",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "27587.6",
      "wattsPerFixture": "203.9",
      "efficacyPerDevice": "135.3",
      "inc": "$400",
      "inc2": "$1,400.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "PKB-200W277-57K-X-T3-Y-Z",
      "reportedLumens": "27587.6",
      "reportedWattage": "203.9",
      "reportedEfficacy": "135.3"
    },
    {
      "proposeMeasure": "PLT_LED243W",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 30,000 lm - 39,999 lm",
      "measureCode": "RL 155",
      "ledManufacturer": "GreenTek Energy Systems",
      "modelNumber": "GT-S-G07-240WCT3A1-[Any Code][P;blank][S;blank][M;blank][AM;DM;YM;A&D]40[Qualified Pointing Straight Down]",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "30856.4",
      "wattsPerFixture": "243.51",
      "efficacyPerDevice": "126.72",
      "inc": "$400",
      "inc2": "$1,400.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "GT-S-G07-240WCT3A1-[Any Code][P;blank][S;blank][M;blank][AM;DM;YM;A&D]40[Qualified Pointing Straight Down]",
      "reportedLumens": "30856.4",
      "reportedWattage": "243.51",
      "reportedEfficacy": "126.72"
    },
    {
      "proposeMeasure": "PLT_LED300W",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 40,000 lm or more",
      "measureCode": "RL 155",
      "ledManufacturer": "GreenTek Energy Systems",
      "modelNumber": "GT-AL2-300W-DLgbdC3-a57Ke",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "41464.9",
      "wattsPerFixture": "300.47",
      "efficacyPerDevice": "138",
      "inc": "$500",
      "inc2": "$1,750.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "GT-AL2-300W-DLgbdC3-a57Ke",
      "reportedLumens": "41464.9",
      "reportedWattage": "300.47",
      "reportedEfficacy": "138"
    },
    {
      "proposeMeasure": "PLT_LED300W_Venas",
      "measureType": "LED Exterior Luminaires",
      "measureDescription": "New LED exterior luminaire - 40,000 lm or more",
      "measureCode": "RL 155",
      "ledManufacturer": "Venas Co., Limited",
      "modelNumber": "SB-300W A3N50T3",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "42000",
      "wattsPerFixture": "300",
      "efficacyPerDevice": "140",
      "inc": "$500",
      "inc2": "$1,750.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "SB-300W A3N50T3",
      "reportedLumens": "42000",
      "reportedWattage": "300",
      "reportedEfficacy": "140"
    },
    {
      "proposeMeasure": "Backlit 2x2",
      "measureType": "LED Troffer Luminaires",
      "measureDescription": "New LED troffer for 2x2 and 1x4 luminaires",
      "measureCode": "RL101",
      "ledManufacturer": "Builders Pack",
      "modelNumber": "LH18-BPL-22-715-840-[S,N][Blank,E]B",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "3629",
      "wattsPerFixture": "28.14",
      "efficacyPerDevice": "128.96",
      "inc": "$75",
      "inc2": "$262.50",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "LH18-BPL-22-715-840-[S,N][Blank,E]B",
      "reportedLumens": "3629",
      "reportedWattage": "28.14",
      "reportedEfficacy": "128.96"
    },
    {
      "proposeMeasure": "Backlit (2x2)_25W_3Klm",
      "measureType": "LED Troffer Luminaires",
      "measureDescription": "New LED troffer for 2x2 and 1x4 luminaires",
      "measureCode": "RL102",
      "ledManufacturer": "Fuchuan Kinlight Co., Ltd",
      "modelNumber": "JL-BPL22-25W-CCT[Blank,-S]-VL[Blank,-BC]",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "3310",
      "wattsPerFixture": "24.8",
      "efficacyPerDevice": "133.4",
      "inc": "$75",
      "inc2": "$262.50",
      "dlcEnergyStarId": "S-QV5WEF",
      "reportedModelNumber": "JL-BPL22-25W-CCT[Blank,-S]-VL[Blank,-BC]",
      "reportedLumens": "3310",
      "reportedWattage": "24.8",
      "reportedEfficacy": "133.4"
    },
    {
      "proposeMeasure": "Backlit 2x2_S(WC)_25W",
      "measureType": "LED Troffer Luminaires",
      "measureDescription": "New LED troffer for 2x2 and 1x4 luminaires",
      "measureCode": "RL101",
      "ledManufacturer": "Fuchuan Kinlight Co., Ltd",
      "modelNumber": "",
      "proposedQty": "JL-BPL22-25W-CCT[Blank,-S]-VH[Blank,-BC]",
      "proposedTotalUnits": "",
      "lumensPerFixture": "3310",
      "wattsPerFixture": "24.8",
      "efficacyPerDevice": "133.4",
      "inc": "$75",
      "inc2": "$262.50",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "0",
      "reportedLumens": "3310",
      "reportedWattage": "24.8",
      "reportedEfficacy": "133.4"
    },
    {
      "proposeMeasure": "Backlit 2x2_S(WC)_20W",
      "measureType": "LED Troffer Luminaires",
      "measureDescription": "New LED troffer for 2x2 and 1x4 luminaires",
      "measureCode": "RL101",
      "ledManufacturer": "Fuchuan Kinlight Co., Ltd",
      "modelNumber": "",
      "proposedQty": "JL-BPL22-20W-CCT[Blank,-S]-VH[Blank,-BC]",
      "proposedTotalUnits": "",
      "lumensPerFixture": "2641",
      "wattsPerFixture": "19.7",
      "efficacyPerDevice": "134.3",
      "inc": "$75",
      "inc2": "$262.50",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "0",
      "reportedLumens": "2641",
      "reportedWattage": "19.7",
      "reportedEfficacy": "134.3"
    },
    {
      "proposeMeasure": "Backlit 2x2_S(WC)_15W",
      "measureType": "LED Troffer Luminaires",
      "measureDescription": "New LED troffer for 2x2 and 1x4 luminaires",
      "measureCode": "RL101",
      "ledManufacturer": "Fuchuan Kinlight Co., Ltd",
      "modelNumber": "",
      "proposedQty": "JL-BPL22-15W-CCT[Blank,-S]-VH[Blank,-BC]",
      "proposedTotalUnits": "",
      "lumensPerFixture": "2003",
      "wattsPerFixture": "14.9",
      "efficacyPerDevice": "134.6",
      "inc": "$75",
      "inc2": "$262.50",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "0",
      "reportedLumens": "2003",
      "reportedWattage": "14.9",
      "reportedEfficacy": "134.6"
    },
    {
      "proposeMeasure": "Backlit 1x4",
      "measureType": "LED Troffer Luminaires",
      "measureDescription": "New LED troffer for 2x2 and 1x4 luminaires",
      "measureCode": "RL101",
      "ledManufacturer": "Builders Pack",
      "modelNumber": "LH-18-BPL-14-715-840-[S,N][Blank,E]B",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "3635",
      "wattsPerFixture": "28.46",
      "efficacyPerDevice": "127.72",
      "inc": "$75",
      "inc2": "$262.50",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "LH-18-BPL-14-715-840-[S,N][Blank,E]B",
      "reportedLumens": "3635",
      "reportedWattage": "28.46",
      "reportedEfficacy": "127.72"
    },
    {
      "proposeMeasure": "Backlit 1x4_S(WC)_15W",
      "measureType": "LED Troffer Luminaires",
      "measureDescription": "New LED troffer for 2x2 and 1x4 luminaires",
      "measureCode": "RL101",
      "ledManufacturer": "Fuchuan Kinlight Co., Ltd",
      "modelNumber": "",
      "proposedQty": "JL-BPL14-15W-CCT[Blank,-S]-VH[Blank,-BC]",
      "proposedTotalUnits": "",
      "lumensPerFixture": "1998",
      "wattsPerFixture": "14.9",
      "efficacyPerDevice": "134.5",
      "inc": "$75",
      "inc2": "$262.50",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "0",
      "reportedLumens": "1998",
      "reportedWattage": "14.9",
      "reportedEfficacy": "134.5"
    },
    {
      "proposeMeasure": "Backlit 2x4_35K",
      "measureType": "LED Troffer Luminaires",
      "measureDescription": "New LED troffer for 2x4 luminaires",
      "measureCode": "RL 102",
      "ledManufacturer": "Builders Pack",
      "modelNumber": "LH18-BPL-24-730-835-[S,N][Blank,E]D",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "3985.6",
      "wattsPerFixture": "31.25",
      "efficacyPerDevice": "127.54",
      "inc": "$100",
      "inc2": "$350.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "LH18-BPL-24-730-835-[S,N][Blank,E]D",
      "reportedLumens": "3985.6",
      "reportedWattage": "31.25",
      "reportedEfficacy": "127.54"
    },
    {
      "proposeMeasure": "Backlit 2x4_4K",
      "measureType": "LED Troffer Luminaires",
      "measureDescription": "New LED troffer for 2x4 luminaires",
      "measureCode": "RL 102",
      "ledManufacturer": "Builders Pack",
      "modelNumber": "LH18-BPL-24-730-840-[S,N][Blank,E]D",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "4007",
      "wattsPerFixture": "31.23",
      "efficacyPerDevice": "128.31",
      "inc": "$100",
      "inc2": "$350.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "LH18-BPL-24-730-840-[S,N][Blank,E]D",
      "reportedLumens": "4007",
      "reportedWattage": "31.23",
      "reportedEfficacy": "128.31"
    },
    {
      "proposeMeasure": "Backlit 2x4_S(WC)_40W",
      "measureType": "LED Troffer Luminaires",
      "measureDescription": "New LED troffer for 2x4 luminaires",
      "measureCode": "RL 102",
      "ledManufacturer": "Fuchuan Kinlight Co., Ltd",
      "modelNumber": "JL-BPL24-40W-CCT[Blank,-S]-VL[Blank,-BC]",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "5291",
      "wattsPerFixture": "39.6",
      "efficacyPerDevice": "133.5",
      "inc": "$100",
      "inc2": "$350.00",
      "dlcEnergyStarId": "S-JSOTUG",
      "reportedModelNumber": "JL-BPL24-40W-CCT[Blank,-S]-VL[Blank,-BC]",
      "reportedLumens": "5291",
      "reportedWattage": "39.6",
      "reportedEfficacy": "133.5"
    },
    {
      "proposeMeasure": "Backlit 2x4_S(WC)_35W",
      "measureType": "LED Troffer Luminaires",
      "measureDescription": "New LED troffer for 2x4 luminaires",
      "measureCode": "RL 102",
      "ledManufacturer": "Fuchuan Kinlight Co., Ltd",
      "modelNumber": "JL-BPL24-35W-CCT[Blank,-S]-VL[Blank,-BC]",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "4644",
      "wattsPerFixture": "34.9",
      "efficacyPerDevice": "134.2",
      "inc": "$100",
      "inc2": "$350.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "JL-BPL24-35W-CCT[Blank,-S]-VL[Blank,-BC]",
      "reportedLumens": "4644",
      "reportedWattage": "34.9",
      "reportedEfficacy": "134.2"
    },
    {
      "proposeMeasure": "Backlit 2x4_S(WC)_30W",
      "measureType": "LED Troffer Luminaires",
      "measureDescription": "New LED troffer for 2x4 luminaires",
      "measureCode": "RL 102",
      "ledManufacturer": "Fuchuan Kinlight Co., Ltd",
      "modelNumber": "JL-BPL24-30W-CCT[Blank,-S]-VL[Blank,-BC]",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "4029",
      "wattsPerFixture": "29.8",
      "efficacyPerDevice": "135.3",
      "inc": "$100",
      "inc2": "$350.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "JL-BPL24-30W-CCT[Blank,-S]-VL[Blank,-BC]",
      "reportedLumens": "4029",
      "reportedWattage": "29.8",
      "reportedEfficacy": "135.3"
    },
    {
      "proposeMeasure": "Backlit 2x4_S(WC)_25W",
      "measureType": "LED Troffer Luminaires",
      "measureDescription": "New LED troffer for 2x4 luminaires",
      "measureCode": "RL 102",
      "ledManufacturer": "Fuchuan Kinlight Co., Ltd",
      "modelNumber": "JL-BPL24-25W-CCT[Blank,-S]-VL[Blank,-BC]",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "3336",
      "wattsPerFixture": "24.8",
      "efficacyPerDevice": "135.1",
      "inc": "$100",
      "inc2": "$350.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "JL-BPL24-25W-CCT[Blank,-S]-VL[Blank,-BC]",
      "reportedLumens": "3336",
      "reportedWattage": "24.8",
      "reportedEfficacy": "135.1"
    },
    {
      "proposeMeasure": "LED Linear Lamp (1T8)",
      "measureType": "LED Replacement Lamps",
      "measureDescription": "Installation of a Type C LED linear lamp and new LED driver",
      "measureCode": "RL 181",
      "ledManufacturer": "Duralife LED",
      "modelNumber": "ZY-T8-18W1200 BIXX-1-C-40K",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "2685.58",
      "wattsPerFixture": "18.8",
      "efficacyPerDevice": "142.85",
      "inc": "$4",
      "inc2": "$14.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "ZY-T8-18W1200 BIXX-1-C-40K",
      "reportedLumens": "2685.58",
      "reportedWattage": "18.8",
      "reportedEfficacy": "142.85"
    },
    {
      "proposeMeasure": "LED Linear Highbay 21Klm_4K_Std_Venas",
      "measureType": "LED High/Low Bay Luminaires",
      "measureDescription": "New LED high/low bay luminaire - 20,000 lm  - 29,999 lm",
      "measureCode": "",
      "ledManufacturer": "Venas Co., Limited",
      "modelNumber": "H5-160W XDZ 4000K",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "21600",
      "wattsPerFixture": "160",
      "efficacyPerDevice": "135",
      "inc": "$300",
      "inc2": "$1,050.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "H5-160W XDZ 4000K",
      "reportedLumens": "21600",
      "reportedWattage": "160",
      "reportedEfficacy": "135"
    },
    {
      "proposeMeasure": "LED Linear Highbay 20Klm_4K_Prm",
      "measureType": "LED High/Low Bay Luminaires",
      "measureDescription": "New LED high/low bay luminaire - 20,000 lm  - 29,999 lm",
      "measureCode": "",
      "ledManufacturer": "GreenTek Energy Systems",
      "modelNumber": "GT-HB07-150WSACGD1-a[S;Blank][M;Blank]40",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "20485.9",
      "wattsPerFixture": "153.38",
      "efficacyPerDevice": "133.56",
      "inc": "$300",
      "inc2": "$1,050.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "GT-HB07-150WSACGD1-a[S;Blank][M;Blank]40",
      "reportedLumens": "20485.9",
      "reportedWattage": "153.38",
      "reportedEfficacy": "133.56"
    },
    {
      "proposeMeasure": "LED Linear Highbay 21Klm_5K_Std",
      "measureType": "LED High/Low Bay Luminaires",
      "measureDescription": "New LED high/low bay luminaire - 20,000 lm  - 29,999 lm",
      "measureCode": "",
      "ledManufacturer": "Builders Pack",
      "modelNumber": "33-LHB-12-7165-850-D-[S, N]-LP",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "21285",
      "wattsPerFixture": "165",
      "efficacyPerDevice": "129",
      "inc": "$300",
      "inc2": "$1,050.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "33-LHB-12-7165-850-D-[S, N]-LP",
      "reportedLumens": "21285",
      "reportedWattage": "165",
      "reportedEfficacy": "129"
    },
    {
      "proposeMeasure": "LED Circular Highbay 22Klm_5K_Prm",
      "measureType": "LED High/Low Bay Luminaires",
      "measureDescription": "New LED high/low bay luminaire - 20,000 lm  - 29,999 lm",
      "measureCode": "",
      "ledManufacturer": "Precision Lighting & Tansformer, Inc",
      "modelNumber": "PLTE72231",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "22500",
      "wattsPerFixture": "150",
      "efficacyPerDevice": "150",
      "inc": "$300",
      "inc2": "$1,050.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "PLTE72231",
      "reportedLumens": "22500",
      "reportedWattage": "150",
      "reportedEfficacy": "150"
    },
    {
      "proposeMeasure": "LED Linear Highbay 11Klm_5K_Prm",
      "measureType": "LED High/Low Bay Luminaires",
      "measureDescription": "New LED high/low bay luminaire - 10,000 lm  - 19,999 lm",
      "measureCode": "",
      "ledManufacturer": "Venas Co., Limited",
      "modelNumber": "ZY-H2-80W XDZ 5000K",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "11121",
      "wattsPerFixture": "81.23",
      "efficacyPerDevice": "137",
      "inc": "$300",
      "inc2": "$1,050.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "ZY-H2-80W XDZ 5000K",
      "reportedLumens": "11121",
      "reportedWattage": "81.23",
      "reportedEfficacy": "137"
    },
    {
      "proposeMeasure": "LED Linear Highbay 11Klm_4K_Prm",
      "measureType": "LED High/Low Bay Luminaires",
      "measureDescription": "New LED high/low bay luminaire - 10,000 lm  - 19,999 lm",
      "measureCode": "",
      "ledManufacturer": "Venas CO., Limited",
      "modelNumber": "ZY-H2-80W XDZ 4000K",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "11121",
      "wattsPerFixture": "81.23",
      "efficacyPerDevice": "137",
      "inc": "$300",
      "inc2": "$1,050.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "ZY-H2-80W XDZ 4000K",
      "reportedLumens": "11121",
      "reportedWattage": "81.23",
      "reportedEfficacy": "137"
    },
    {
      "proposeMeasure": "Top_Post_151W",
      "measureType": "LED Troffer Luminaires",
      "measureDescription": "New LED exterior luminaire - 20,000 lm - 29,999 lm",
      "measureCode": "Top Post",
      "ledManufacturer": "RuggedGrade",
      "modelNumber": "RGLCENTAURI2-150WSBT2GA1-a[MS;Blank][10SP;20SP;Blank]d50",
      "proposedQty": "",
      "proposedTotalUnits": "",
      "lumensPerFixture": "20259.1",
      "wattsPerFixture": "151.32",
      "efficacyPerDevice": "133.89",
      "inc": "$350",
      "inc2": "$1,225.00",
      "dlcEnergyStarId": "",
      "reportedModelNumber": "RGLCENTAURI2-150WSBT2GA1-a[MS;Blank][10SP;20SP;Blank]d50",
      "reportedLumens": "20259.1",
      "reportedWattage": "151.32",
      "reportedEfficacy": "133.89"
    }
  ]
};
