(function attachSpaceTypes(global) {
  const spaceTypes = [
  "Atrium- (Less than 40 ft height)",
  "Atrium- (Greater than 40 ft height)",
  "Audience Seating Area - Auditorium",
  "Audience Seating Area - Convention Center",
  "Audience Seating Area - Gymnasium",
  "Audience Seating Area - Motion Picture Theater",
  "Audience Seating Area - Otherwise",
  "Building Facades",
  "Uncovered Parking Areas and Driveways",
  "Audience Seating Area - Religious Buildings",
  "Audience Seating Area - Sports Arena",
  "Banking Activity Area",
  "Classroom / Lecture Hall / Training room - Otherwise",
  "Classroom / Lecture Hall / Training room - Penitentiary",
  "Computer room",
  "Conference / Meeting Room / Multipurpose",
  "Convention Center / exhibit space",
  "Copy/print room",
  "Corridor /  - Hospital",
  "Corridor /  - Manufacturing Facility",
  "Corridor / - Otherwise",
  "Corridor / for visually impaired and not used primarily by the staff",
  "Courtroom",
  "Dining Area - Bar/Lounge/Leisure Dining",
  "Dining Area - Cafeteria or fast food dining",
  "Dining Area - Family dining",
  "Dining Area - for visually impaired and not used primarily by the staff",
  "Dining Area - Otherwise",
  "Dining Area - Penitentiary",
  "Dormitory - living quarters",
  "Electrical / Mechanical Room",
  "Emergency vehicle garage",
  "Facility for visually impaired - in chapel and not used primarily by the staff",
  "Facility for visually impaired - in recreation room and not used primarily by the staff",
  "Fire station -sleeping quarters",
  "Food Preparation area",
  "Guest room",
  "Gymnasium / fitness center - in a playing area",
  "Gymnasium / fitness center - in an exercise area",
  "Health care facility - in a nursery",
  "Health care facility - in a nurse's station",
  "Health care facility - in a patient room",
  "Health care facility - in a physical therapy room",
  "Health care facility - in a recovery room",
  "Health care facility - in an exam /treatment room",
  "Health care facility - in an imagining room",
  "Health care facility - in an operating room",
  "Health care facility - in medical supply room",
  "Laboratory - for Classrooms",
  "Laboratory - Otherwise",
  "Laundry / Washing area",
  "Library - In a reading area",
  "Library - In the stacks",
  "Loading dock , interior",
  "Lobby - Elevator",
  "Lobby - for visually impaired and not used primarily by the staff",
  "Lobby - Hotel",
  "Lobby - Motion Picture Theater",
  "Lobby - Otherwise",
  "Lobby - Performing Arts Theater",
  "Locker room",
  "Lounge/breakroom - in healthcare facility",
  "Lounge/breakroom - Otherwise",
  "Manufacturing - Detailed Manufacturing",
  "Manufacturing - Equipment Room",
  "Manufacturing Extra High Bay (>50 FT Flr to Clg Hgt)",
  "Manufacturing High Bay (25-50 FT Floor to Ceiling Hgt)",
  "Manufacturing Lowbay (<25 FT Floor to Ceiling Hgt)",
  "Museum - General Exhibition Area",
  "Museum - Restoration room",
  "Office - Enclosed",
  "Office - Open Plan",
  "Parking area , interior",
  "Performing arts theather - dressing room",
  "Pharmacy area",
  "Post Office - Sorting Area",
  "Religious Buildings - Fellowship Hall",
  "Religious Buildings - Worship Pulpit, Choir",
  "Restrooms - for visually impaired and not used primarily by the staff",
  "Restrooms - Otherwise",
  "Retail - Dressing / Fitting Room",
  "Retail - Mall Concourse",
  "Sales area",
  "Seating area , general",
  "Sports arena - playing area  for a class III facility",
  "Sports arena - playing area for a class I facility",
  "Sports arena - playing area for a class II facility",
  "Sports arena - playing area for a class IV facility",
  "Stairwell",
  "Storage room",
  "Transportation -  Baggage / Carousel Area",
  "Transportation - Airport Concourse",
  "Transportation - Terminal Ticket Counter",
  "Vacant",
  "Vehicular maintenance area",
  "Warehouse Storage - Medium/ Bulky Palletized Material",
  "Warehouse Storage - Small hand carry items",
  "Workshop",
  "ATMs and Night Depositories",
  "Drive-Through Windows",
  "Emergency Loading Areas",
  "Building Entrances and Exits- Entry Canopies",
  "Gatehouses at Guarded Facilities",
  "Landscaping",
  "Loading Docks",
  "Building Entrances and Exits- Main Entries",
  "Outdoor Sales- Open Sales Areas",
  "Building Entrances and Exits- Other Doors",
  "Parking near 24-hours Retail Entrances",
  "Pedestrian Tunnels",
  "Sales Canopies",
  "Stairways",
  "Walkways 10 feet or wider, Plazas, or Special Feature Area",
  "Walkways less than 10 feet wide"
];
  const rules = [
    [/atrium/i, 'Atrium- (Less than 40 ft height)'],
    [/auditorium/i, 'Audience Seating Area - Auditorium'],
    [/movie|motion picture|cinema/i, 'Audience Seating Area - Motion Picture Theater'],
    [/gym.*play|basketball|court/i, 'Gymnasium / fitness center - in a playing area'],
    [/gym|fitness|exercise/i, 'Gymnasium / fitness center - in an exercise area'],
    [/class|lecture|training/i, 'Classroom / Lecture Hall / Training room - Otherwise'],
    [/computer|server|it room/i, 'Computer room'],
    [/conference|meeting|multipurpose/i, 'Conference / Meeting Room / Multipurpose'],
    [/copy|print/i, 'Copy/print room'],
    [/corridor|hallway|hall(?!.*fellowship)/i, 'Corridor / - Otherwise'],
    [/courtroom/i, 'Courtroom'],
    [/bar|lounge dining/i, 'Dining Area - Bar/Lounge/Leisure Dining'],
    [/cafeteria|fast food/i, 'Dining Area - Cafeteria or fast food dining'],
    [/dining|restaurant/i, 'Dining Area - Otherwise'],
    [/dorm|living quarter/i, 'Dormitory - living quarters'],
    [/electrical|mechanical|boiler|utility room/i, 'Electrical / Mechanical Room'],
    [/kitchen|food prep/i, 'Food Preparation area'],
    [/guest room|hotel room/i, 'Guest room'],
    [/nursery/i, 'Health care facility - in a nursery'],
    [/nurse/i, "Health care facility - in a nurse's station"],
    [/patient room/i, 'Health care facility - in a patient room'],
    [/physical therapy/i, 'Health care facility - in a physical therapy room'],
    [/recovery/i, 'Health care facility - in a recovery room'],
    [/exam|treatment/i, 'Health care facility - in an exam /treatment room'],
    [/imag(e|ing)|x-ray|radiology/i, 'Health care facility - in an imagining room'],
    [/operating|surgery/i, 'Health care facility - in an operating room'],
    [/medical supply/i, 'Health care facility - in medical supply room'],
    [/laboratory|lab/i, 'Laboratory - Otherwise'],
    [/laundry|washing/i, 'Laundry / Washing area'],
    [/library.*stack|book stack/i, 'Library - In the stacks'],
    [/library|reading/i, 'Library - In a reading area'],
    [/loading dock/i, 'Loading dock , interior'],
    [/elevator lobby/i, 'Lobby - Elevator'],
    [/hotel lobby/i, 'Lobby - Hotel'],
    [/lobby|reception/i, 'Lobby - Otherwise'],
    [/locker/i, 'Locker room'],
    [/break.?room|employee lounge/i, 'Lounge/breakroom - Otherwise'],
    [/manufactur.*equipment/i, 'Manufacturing - Equipment Room'],
    [/manufactur|production/i, 'Manufacturing Lowbay (<25 FT Floor to Ceiling Hgt)'],
    [/museum|exhibit/i, 'Museum - General Exhibition Area'],
    [/open office|open plan/i, 'Office - Open Plan'],
    [/office|admin/i, 'Office - Enclosed'],
    [/interior parking|parking garage|garage parking/i, 'Parking area , interior'],
    [/pharmacy/i, 'Pharmacy area'],
    [/sorting|post office/i, 'Post Office - Sorting Area'],
    [/fellowship/i, 'Religious Buildings - Fellowship Hall'],
    [/church|chapel|sanctuary|worship|pulpit|choir/i, 'Religious Buildings - Worship Pulpit, Choir'],
    [/restroom|bathroom|toilet/i, 'Restrooms - Otherwise'],
    [/dressing|fitting/i, 'Retail - Dressing / Fitting Room'],
    [/mall|concourse/i, 'Retail - Mall Concourse'],
    [/sales|retail|showroom|store/i, 'Sales area'],
    [/stair/i, 'Stairwell'],
    [/storage|stock room|closet/i, 'Storage room'],
    [/vehicle|auto|repair|service bay/i, 'Vehicular maintenance area'],
    [/warehouse.*small|small parts/i, 'Warehouse Storage - Small hand carry items'],
    [/warehouse/i, 'Warehouse Storage - Medium/ Bulky Palletized Material'],
    [/workshop|shop/i, 'Workshop'],
    [/atm|night depos/i, 'ATMs and Night Depositories'],
    [/facade|wall pack|building wall/i, 'Building Facades'],
    [/drive.?through/i, 'Drive-Through Windows'],
    [/emergency loading/i, 'Emergency Loading Areas'],
    [/canopy/i, 'Building Entrances and Exits- Entry Canopies'],
    [/guard|gatehouse/i, 'Gatehouses at Guarded Facilities'],
    [/landscap/i, 'Landscaping'],
    [/main entr|front entr/i, 'Building Entrances and Exits- Main Entries'],
    [/entrance|exit|door/i, 'Building Entrances and Exits- Other Doors'],
    [/outdoor sales/i, 'Outdoor Sales- Open Sales Areas'],
    [/parking|driveway|lot/i, 'Uncovered Parking Areas and Driveways'],
    [/tunnel/i, 'Pedestrian Tunnels'],
    [/walkway|sidewalk/i, 'Walkways less than 10 feet wide']
  ];
  function suggestSpaceType(location, area) {
    const text = String(location || '').trim();
    for (const [pattern, value] of rules) if (pattern.test(text)) return value;
    if (String(area || '').toLowerCase() === 'exterior') return 'Uncovered Parking Areas and Driveways';
    return '';
  }
  global.EWPROS_SPACE_TYPES = { spaceTypes, suggestSpaceType };
})(typeof window !== 'undefined' ? window : globalThis);
