(()=>{
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const endpoint='/.netlify/functions/worker-timesheet'; let auth=JSON.parse(sessionStorage.getItem('ewpros_timesheet_auth')||'null'), model=null;
const today=()=>new Date().toISOString().slice(0,10); $('#timeForm [name="work_date"]').value=today();
async function call(payload){const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...payload,...auth})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed.');return d;}
function fillSelect(el,rows,label){const current=el.value;const first=el.id==='project'?'<option value="">No project</option>':'';el.innerHTML=first+rows.map(r=>`<option value="${esc(r.id)}">${esc(label(r))}</option>`).join('');if([...el.options].some(o=>o.value===current))el.value=current;}
function render(d){model=d;$('#loginPanel').classList.add('hidden');$('#portal').classList.remove('hidden');$('#logout').classList.remove('hidden');$('#workerName').textContent=`${d.worker.first_name} ${d.worker.last_name} · ${d.worker.worker_type}`;fillSelect($('#project'),d.projects,r=>`${r.project_number?`${r.project_number} — `:''}${r.name}${r.customers?.display_name?` · ${r.customers.display_name}`:''}`);fillSelect($('#businessLine'),d.businessLines,r=>r.name);$('#entries').innerHTML=d.entries.length?`<table><thead><tr><th>Date</th><th>Project</th><th>Regular</th><th>OT</th><th>Status</th></tr></thead><tbody>${d.entries.map(r=>`<tr><td>${esc(r.work_date)}</td><td>${esc(r.projects?.name||r.business_lines?.name||'—')}</td><td>${esc(r.regular_hours)}</td><td>${esc(r.overtime_hours)}</td><td><span class="badge">${esc(r.approval_status)}</span></td></tr>`).join('')}</tbody></table>`:'<p>No entries yet.</p>';}
async function login(){if(!auth)return;try{render(await call({action:'login'}));}catch{sessionStorage.removeItem('ewpros_timesheet_auth');auth=null;}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';const f=new FormData(e.currentTarget);auth={email:f.get('email'),pin:f.get('pin')};try{const d=await call({action:'login'});sessionStorage.setItem('ewpros_timesheet_auth',JSON.stringify(auth));render(d);}catch(err){auth=null;$('#loginError').textContent=err.message;}});
$('#project').addEventListener('change',()=>{const p=model?.projects?.find(x=>x.id===$('#project').value);if(p)$('#businessLine').value=p.business_line_id;});
$('#timeForm').addEventListener('submit',async e=>{e.preventDefault();const msg=$('#formMessage');msg.textContent='';const f=Object.fromEntries(new FormData(e.currentTarget).entries());try{render(await call({action:'submit',...f}));msg.textContent='Time submitted for approval.';e.currentTarget.elements.regular_hours.value='0';e.currentTarget.elements.overtime_hours.value='0';e.currentTarget.elements.notes.value='';}catch(err){msg.textContent=err.message;}});
$('#logout').addEventListener('click',()=>{sessionStorage.removeItem('ewpros_timesheet_auth');location.reload();});login();
})();
